services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: db_test_sql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - mynetwork
  
  app:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/db_test_sql
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
